// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrencyController from "./currency_controller"
application.register("currency", CurrencyController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndexationController from "./indexation_controller"
application.register("indexation", IndexationController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
